name = "uri_ada"
description = "Processing of URI strings"
version = "1.0.0"
licenses = "LGPL-3.0-only"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]

tags = ["uri", "url", "utility"]

project-files = ["uri.gpr"]

[origin]
commit = "84a01e5c72a735cbda50bde77cfe77008e06d9cf"
url = "git+https://github.com/mosteo/uri-ada.git"

