description = "WS-Security 1.1 implementation for SOAP 1.2"
name = "matreshka_soap_wsse"
version = "21.0.0"
website = "https://github.com/godunko/matreshka"
authors = ["Vadim Godunko"]
licenses = "BSD-3-Clause"
maintainers = ["Vadim Godunko <vgodunko@gmail.com>", "Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko", "reznikmm"]
project-files = ["build_matreshka_soap_wsse.gpr"]
tags = ["soap", "wsse", "web"]

[[depends-on]]
matreshka_league = "21.0.0"
matreshka_soap = "21.0.0"

[origin]
url = "git+https://github.com/reznikmm/matreshka-alire"
commit = "2a4cb0c0f17201bc8e116706a9db4adc78f7d644"
