[general]
description = "Experimental YAML 1.3 implementation in Ada (server component)"
licenses = ["MIT"]
authors = ["Felix Krause"]
maintainers = ["alejandro@mosteo.com"]
website = "https://ada.yaml.io/"

project-files = ["yaml-server.gpr"]
executables = ["yaml-server"]

    [general.depends-on]
    aunit = "^2017"
    gnatcoll_connections = "^4.27"

    [general.gpr-externals]
    Mode = ["debug", "release"]

['0.3']
origin = "git+https://github.com/yaml/AdaYaml.git@2017a7c2523499c03b8d7fe06546a5a8bae6476d"
