description = "MySQL binding for Ada"
name = "matreshka_sql_mysql"
version = "21.0.0"
website = "https://github.com/godunko/matreshka"
authors = ["Vadim Godunko"]
licenses = "BSD-3-Clause"
maintainers = ["Vadim Godunko <vgodunko@gmail.com>", "Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko", "reznikmm"]
project-files = ["build_matreshka_sql_mysql.gpr"]
tags = ["sql", "database", "db", "mysql", "mariadb"]

[[depends-on]]
libmysqlclient = "any"
matreshka_league = "21.0.0"
matreshka_sql = "21.0.0"

[origin]
url = "git+https://github.com/reznikmm/matreshka-alire"
commit = "e880d413a557f324505cf8fdf2857c38a3007b37"
