description = "MySQL binding for Ada"
name = "matreshka_sql_mysql"
version = "20.1.0"
website = "https://github.com/godunko/matreshka"
authors = ["Vadim Godunko"]
licenses = "BSD-3-Clause"
maintainers = ["Vadim Godunko <vgodunko@gmail.com>", "Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko", "reznikmm"]
project-files = ["build_matreshka_sql_mysql.gpr"]
tags = ["sql", "database", "db", "mysql", "mariadb"]

[[depends-on]]
libmysqlclient = "any"
matreshka_league = "20.1.0"
matreshka_sql = "20.1.0"

[origin]
# NOTE: Use the same dummy archive to build subproject as in 18.1
url = "https://github.com/reznikmm/matreshka-alire/archive/matreshka_sql_mysql-18.1.tar.gz"
hashes = ["sha512:0e1d8df48521ceb79bb74081c8d4d79980c47711040468cf6f0a07abb136db4dfe3fd84bf3e01df3482d8c110fdb17086ac7e48716aa03928ef6a8baf61e750d"]
