description = "SQLite binding for Ada"
name = "matreshka_sql_sqlite3"
version = "21.0.0"
website = "https://github.com/godunko/matreshka"
authors = ["Vadim Godunko"]
licenses = "BSD-3-Clause"
maintainers = ["Vadim Godunko <vgodunko@gmail.com>", "Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko", "reznikmm"]
project-files = ["build_matreshka_sql_sqlite3.gpr"]
tags = ["sql", "database", "db", "sqlite"]

[[depends-on]]
libsqlite3 = "any"
matreshka_league = "21.0.0"

[origin]
url = "git+https://github.com/reznikmm/matreshka-alire"
commit = "0ae8347db103c231d60bc4b795461aa4e6c73696"
