name                = "mos6502_create_led"
description         = "Create ROM with little program"
long-description    = """This is a tool to create a rom image with little program.

This program can be used to create a ROM immage for the MOS 6502 tutorial
from Ben Eater.

Development versions available with:

alr index --add "git+https://github.com/krischik/alire-index.git#develop" --name krischik
"""
version             = "1.0.0"
licenses            = "GPL-3.0-or-later"
authors             = ["Martin Krischik <krischik@users.sourceforge.net>"]
maintainers         = ["Martin Krischik <krischik@users.sourceforge.net>"]
maintainers-logins  = ["krischik"]
executables         = ["create_led"]
website             = "https://sourceforge.net/projects/tutorial-6502"
tags                = ["mos-6502", "tools", "retrocomputing", "ada2022"]

[[depends-on]]
gnat                = ">=12 & <2000"

# vim: set textwidth=0 nowrap tabstop=8 shiftwidth=4 softtabstop=4 expandtab :
# vim: set filetype=toml fileencoding=utf-8 fileformat=unix foldmethod=diff :
# vim: set spell spelllang=en_gb :

[origin]
hashes = [
"sha256:54914b606737258e3ca19665ddbbab243c705268dd5dd96a34950d7bc078c7f3",
"sha512:265ed7bcc771325c61518e59631fa12cf3246e783bfd6cdc86a8db18e4c444cecbec66247a8be2c7bd0f007c568c7a1fe2fb6ab8748a71c5e0701b0f55f8e469",
]
url = "https://sourceforge.net/projects/tutorial-6502/files/Alire/mos6502_create_led-1.0.0.tgz"

