name = "wordlist"
description = "An English word list"
version = "0.1.3"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]

licenses = "MIT"
tags = ["wordlist", "english"]

[[depends-on]]
aaa       = "~0.2.5"
ada_toml  = "~0.3.0"
gnat      = ">=11 & <2000"
resources = "~0.1.0"

[configuration.variables]
Logging = { type = "Boolean", default = false }
Wordset = { type = "Enum", values = ["small", "large", "wordle"], default = "large" }

[origin]
commit = "fad16afcc384075bd0fda36d98b95d78778e46c7"
url = "git+https://github.com/mosteo/wordlist_ada.git"

