name = "vss"
description = "Advanced string and text manipulation with Unicode support"
version = "23.0.0"
tags = ["unicode", "json", "text", "xml", "template"]

authors = ["AdaCore"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>", "Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko", "reznikmm"]
licenses = "Apache-2.0"
website = "https://github.com/AdaCore/VSS"

project-files = ["gnat/vss_text.gpr", "gnat/vss_json.gpr", "gnat/vss_regexp.gpr", "gnat/vss_xml.gpr", "gnat/vss_xml_templates.gpr"]

[configuration]
disabled = true

[origin]
archive-name = "vss-23.0.0.tar.gz"
url = "https://github.com/AdaCore/VSS/archive/refs/tags/v23.0.0.tar.gz"
hashes = ["sha512:11e762a6ade7137acb32c0776db06244b40a137df90ee5d25855503deeba2a22e6e962ed56d991c71fd27a514edca22ff3d35b0f783855e2d670eb6b45aa4c03"]

[[depends-on]]
gnat = ">=12 & <=2000"
