description = "Experimental YAML 1.3 implementation in Ada"
name = "adayaml"
version = "0.3.0"
website = "https://ada.yaml.io/"
authors = ["Felix Krause"]
executables = ["yaml-server"]
licenses = ["MIT"]
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]
project-files = ["yaml.gpr", "yaml-utils.gpr", "yaml-annotation_processor.gpr", "yaml-server.gpr"]

[[depends-on]]
simple_components = "^4.27"

[gpr-externals]
Mode = ["debug", "release"]

[origin]
url = "https://github.com/yaml/AdaYaml/archive/v0.3.0.tar.gz"
hashes = ["sha512:ab19e38704e5d51a3f66da2fb9f86571ab08a6793a5d5f42ca29c3271bc754a1a845cc831d7fb24bb19c2caaf0d355ba250d0dca2959607a19936b0a91739d33"]
