[general]
description = "Templates Parser: File generation from templates in Ada"
licenses = ["GPL 3.0"]
authors = ["AdaCore"]
website = "https://github.com/AdaCore/templates-parser"
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

    [general.gpr-externals]
    PRJ_BUILD = ["Debug", "Release"]
    TP_TASKING = ["No_Tasking" ,"Standard_Tasking"]
    TP_XMLADA = ["Installed", "Disabled"]
    LIBRARY_TYPE = ["static", "relocatable"]

    # We configure it with external xmlada, 
    # so other projects depending on xmlada do not clash

    [general.gpr-set-externals]
    TP_XMLADA = "Installed"

    [[general.actions]]
    type = "post-fetch"
    command = "cp config/tp_xmlada_installed.gpr tp_xmlada.gpr"

['17.2']
origin = "https://github.com/AdaCore/templates-parser/archive/17.2.tar.gz"
origin-hashes = ["sha512:997a4ca50fef45846b125813ae2b5863632fa45120f7fc97fe501fd712049c5cde6544ce4df35f5d6a0064137507a9f35b0baffd3c07339adb4058705dce6178"]

    ['17.2'.depends-on]
    xmlada = "any"
