name = "orka_tensors_gpu"
description = "Tensors using compute shaders on the GPU"
version = "1.0.0"
website = "https://github.com/onox/orka"
licenses = "Apache-2.0"
tags = ["orka", "math", "vector", "matrix", "ndarray", "tensor", "numpy", "random", "statistics", "leastsquares", "linearalgebra", "linalg", "gpu", "gpgpu", "compute", "shaders"]

authors = ["onox"]
maintainers = ["onox <denkpadje@gmail.com>"]
maintainers-logins = ["onox"]

[build-switches]
validation.compile_checks = "warnings"
"*".style_checks = ["-gnatygAOM99-Is"]

[[depends-on]]
orka = "~1.0.0"
orka_numerics = "~1.0.0"
orka_types = "~1.0.0"
gnat = ">=12"

[origin]
commit = "b455160b0b24a89af4ae6423b186dc826915d487"
url = "git+https://github.com/onox/orka.git"
subdir = "orka_tensors_gpu"
