description = "League - universal string library. Part of Matreshka framework"
name = "matreshka_league"
version = "18.1.0"
website = "https://forge.ada-ru.org/matreshka"
authors = ["Vadim Godunko"]
licenses = ["BSD 3-Clauses"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>", "Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko", "reznikmm"]
project-files = ["gnat/matreshka_league.gpr"]
tags = ["unicode", "xml", "sax", "json", "encoding", "regexp", "time"]

[[actions]]
type = "post-fetch"
command = ["make", "reconfig"]

[[depends-on]]
make = "any"

[origin]
url = "http://forge.ada-ru.org/matreshka/downloads/matreshka-18.1.tar.gz"
archive-name = "matreshka-18.1.tar.gz"
hashes = ["sha512:4fab6c039550017f6cd16d6216f76e9651f1fd5c24d842cccd5ca1340733216ff5dca4aea8babd6c43da8bb75db94681b398f3c04c2a7e4cca7ae49a7c56aa76"]
