description = "The GNU Readline Library"
name = "liblzma"
licenses = "GPL-2.0-or-later AND GPL-3.0-or-later AND LGPL-2.1-or-later"
maintainers = ["chouteau@adacore.com"]
maintainers-logins = ["Fabien-Chouteau"]

[[external]]
kind = "system"
[external.origin."case(distribution)"]
"debian|ubuntu" = ["liblzma-dev"]
