name = "ada_fuse"
version = "1.0.0"
description = "Ada bindings for Fuse (Filesystem in Userspace)"
website = "https://github.com/medsec/ada-fuse"
authors  = [
    "Alexander Herr <thissideup@riseup.net>",
    "Nicolai Ruckel <nicolai.ruckel@uni-weimar.de>",
    "christopher-l <christopher.luebbemeier@googlemail.com>"
    ]
maintainers = ["Nicolai Ruckel <nicolai.ruckel@uni-weimar.de>"]
maintainers-logins = [
    "NicolaiRuckel", "medsec"
]
licenses = "GPL-3.0-only"
project-files = ["ada_fuse.gpr"]

[gpr-externals]
ADA_FUSE_SYSTEM = ["Linux x86_64", "Linux i386", "Darwin i386", "Darwin x86_64"]

[gpr-set-externals.'case(os)']
linux = { ADA_FUSE_SYSTEM = "Linux x86_64" }
macos = { ADA_FUSE_SYSTEM = "Darwin x86_64" }

[available.'case(os)']
linux   = true
macos   = true
windows = false
'...'   = false

[origin]
url = "https://github.com/medsec/ada-fuse/archive/v1.0.zip"
hashes = ["sha512:8e67aaa8f57b688231e7d2cda0d02093c8d1d3c9a47729af613c95a1262f5ef24af0196a83b6d5c74bc43097846a514ce11c5d680ef74b8f31526752c239a11a"]

[[depends-on]]
libfuse = "^2.0.0"
