name = "muntsos_dev_beaglebone"
description = "MuntsOS Embedded Linux BeagleBone ARMv7 cross-toolchain metapackage"
tags = ["muntsos", "embedded", "linux", "arm", "beaglebone"]
website = "https://github.com/pmunts/muntsos"

maintainers = ["Philip Munts <phil@munts.net>"]
maintainers-logins = ["pmunts"]

[[external]]
kind = "system"
hint = "Available at http://repo.munts.com/debian11 or http://repo.munts.com/muntsos/rpms"
[external.origin."case(distribution)"]
"centos|debian|fedora|rhel|ubuntu" = ["muntsos-dev-beaglebone"]
