description = "Simple DirectMedia Layer development files - TTF"
name = "libsdl2_ttf"

maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

[[external]]
kind = "system"
    [external.origin.'case(distribution)']
    'debian|ubuntu' = ["libsdl2-ttf-dev"]
    'arch' = ["sdl2_ttf"]
    'homebrew' = ["sdl2_ttf"]
    'macports' = ["libsdl2_ttf"]
    'msys2' = ["mingw-w64-x86_64-SDL2_ttf"]
