description = "Libraries for use with PostgreSQL"
name = "libpq"

maintainers = ["Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]

[[external]]
kind = "system"
[external.origin."case(distribution)"]
"fedora" = ["libpq-devel"]
"debian|ubuntu" = ["libpq-dev"]
"msys2" = ["mingw-w64-x86_64-postgresql"]
