description = "Mandelbrot renderer using Unicode glyphs"
name = "mandelbrot_ascii"
version = "1.0.0"
authors = ["David Given"]
licenses = []
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]

[origin]
url = "https://github.com/mosteo/mandelbrot_ascii/archive/v1.0.tar.gz"
hashes = ["sha512:974d55bd22891e95195e725846538b7a78272e7f3d60196aa495939014a3a64b63230abe854f6a7e1f549ea2855849b15bd245a9888b8a6a587b77084782bb11"]
