description = "Web Servlet Library following JSR 154, JSR 315 (Core)"
name = "servletada"
version = "1.3.0"
origin = "https://github.com/stcarrez/ada-servlet/archive/1.3.0.tar.gz"
licenses = ["Apache 2.0"]
maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]
project-files = [".alire/servletada.gpr"]
origin-hashes = ["sha512:7ba99a77dea06e058367504b9cd8bf39599f237f09128b1cac1aa55cc067f0380df6e76de374642e89ea1f4a1a4770c1048d40ad7ff5e6f3aaa42415ad5b7082"]

[[actions]]
type = "post-fetch"
command = ["rm", "-f", "config.gpr"]

[[depends-on]]
security = "^1.2.1"
utilada = "^2.0.0"

[gpr-externals]
BUILD = ["distrib", "debug", "optimize", "profile", "coverage"]
SERVLET_LIBRARY_TYPE = ["relocatable", "static", "static-pic"]
