name = "pico_bsp"
description = "Board support package for Raspberry Pi Pico"
version = "1.5.0"
licenses = "BSD-3-Clause"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
tags = ["embedded", "nostd", "raspberrypi", "pico", "rp2040", "bsp"]
website = "https://pico-doc.synack.me/"

[[depends-on]]
hal = "~0.1"
rp2040_hal = "^1.5"

[configuration.values]
rp2040_hal.Flash_Chip = "w25qxx"

[origin]
commit = "22a7257552168a489f514bc4da65cbc641985b60"
url = "git+https://github.com/JeremyGrosser/pico_bsp.git"

