description = "Security Library for HTTP client and server with OAuth2 support"
name = "security"
version = "1.5.0"
licenses = "Apache-2.0"
maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]
authors = ["Stephane.Carrez@gmail.com"]
project-files = [".alire/security.gpr"]
tags = ["security", "oauth2", "authentication", "permissions", "jwt"]
website = "https://gitlab.com/stcarrez/ada-security"
long-description = """

[![Build Status](https://img.shields.io/endpoint?url=https://porion.vacs.fr/porion/api/v1/projects/ada-security/badges/build.json)](https://porion.vacs.fr/porion/projects/view/ada-security/summary)
[![Test Status](https://img.shields.io/endpoint?url=https://porion.vacs.fr/porion/api/v1/projects/ada-security/badges/tests.json)](https://porion.vacs.fr/porion/projects/view/ada-securit/xunits)
[![Coverage](https://img.shields.io/endpoint?url=https://porion.vacs.fr/porion/api/v1/projects/ada-security/badges/coverage.json)](https://porion.vacs.fr/porion/projects/view/ada-security/summary)
[![Documentation Status](https://readthedocs.org/projects/ada-security/badge/?version=latest)](https://ada-security.readthedocs.io/en/latest/?badge=latest)

Ada Security provides a security framework which allows applications to define
and enforce security policies. This framework allows users to authenticate by using
[OpenID Authentication 2.0](https://openid.net/specs/openid-authentication-2_0.html)
as well as [OAuth 2.0](https://oauth.net/2/) protocol.
It allows a web application to integrate easily with Yahoo!, Gitlab, Github, Facebook and
Google+ authentication systems.
The Ada05 library includes:

* An OpenID client authentication,
* An OAuth 2.0 client authentication,
* An OpenID Connect authentication framework,
* An OAuth 2.0 server authentication framework,
* A policy based security framework to protect the resources

The Ada Security library is used by the
[Ada Web Application](https://gitlab.com/stcarrez/ada-awa)
to provide authentication and access control to users within the web applications.

## Documentation

* [Ada Security Programmer's Guide](https://ada-security.readthedocs.io/en/latest/)

"""

[[depends-on]]
utilada = "^2.6.0"
utilada_xml = "^2.6.0"

[gpr-externals]
SECURITY_BUILD = ["distrib", "debug", "optimize", "profile", "coverage"]
SECURITY_LIBRARY_TYPE = ["relocatable", "static", "static-pic"]

[configuration]
disabled = true

[origin]
commit = "0092ca1437ad842e4166780cefbcd1157977c3c9"
url = "git+https://gitlab.com/stcarrez/ada-security.git"

