auto-gpr-with = false
description = "Bindings for the LVGL embedded GUI framework"
name = "lvgl_ada"
version = "0.1.0"
origin = "https://github.com/Fabien-Chouteau/lvgl-ada/releases/download/v0.1.0/lvgl_ada-0.1.0.zip"
licenses = ["MIT"]
maintainers = ["fabien.chouteau@gmail.com"]
maintainers-logins = ["Fabien-Chouteau"]
project-files = ["lvgl_ada_1bit_color.gpr", "lvgl_ada_8bit_color.gpr", "lvgl_ada_16bit_color.gpr", "lvgl_ada_32bit_color.gpr"]
tags = ["embedded", "gui", "lvgl", "no-std"]
origin-hashes = ["sha512:997edc53060b3e818f3ec306d234c8041c7719a48c6a4f0228624827a8f5ff0e93139c3d19be2558af2f6829ae62259b271b3a2582ba10ef09b38868b5da0242"]
