name = "avrada_mcu"
description = "Device (MCU) specific definitions for AVR microcontrollers"
version = "2.0.0"

authors = ["Rolf Ebert"]
maintainers = ["Rolf Ebert <rolf.ebert.gcc@gmx.de>"]
maintainers-logins = ["RREE"]
licenses = "GPL-2.0-or-later WITH GCC-exception-3.1"
website = "https://sourceforge.net/projects/avr-ada/"
tags = ["avr", "embedded", "rts"]

[[depends-on]]
gnat_avr_elf = "^11"
avrada_rts = "^2.0.0"


[origin]
commit = "49c53cffa9e6229e4f39d9edf0d3fc5122d29124"
url = "git+https://github.com/RREE/AVRAda_MCU.git"

