description = "Web-application server. Implementation library"
name = "matreshka_spikedog_core"
version = "18.1.0"
website = "https://forge.ada-ru.org/matreshka"
authors = ["Vadim Godunko"]
licenses = ["BSD 3-Clauses"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>", "Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko", "reznikmm"]
project-files = ["build_matreshka_spikedog_core.gpr"]
tags = ["web", "servlet"]

[[depends-on]]
matreshka_league = "any"
matreshka_spikedog_api = "any"

[origin]
url = "https://github.com/reznikmm/matreshka-alire/archive/matreshka_spikedog_core-18.1.tar.gz"
hashes = ["sha512:1614d389245f8d6ec5a756a5c42b13d48296f64f1e54706fa9063fb67b0bc01f92c808d49e0d2855fadbb3648c2a46e677d38686d908c8259ebfa7d8d6ad4140"]
