description = "Web-application server. Implementation library"
name = "matreshka_spikedog_core"
version = "21.0.0"
website = "https://github.com/godunko/matreshka"
authors = ["Vadim Godunko"]
licenses = "BSD-3-Clause"
maintainers = ["Vadim Godunko <vgodunko@gmail.com>", "Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko", "reznikmm"]
project-files = ["build_matreshka_spikedog_core.gpr"]
tags = ["web", "servlet"]

[[depends-on]]
matreshka_league = "21.0.0"
matreshka_spikedog_api = "21.0.0"

[origin]
url = "git+https://github.com/reznikmm/matreshka-alire"
commit = "8932a8f4aec45d6818176162c5632f7df81ae688"
