name = "usb_embedded"
description = "An Ada USB stack for embedded devices"
version = "0.1.0"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <chouteau@adacore.com>"]
maintainers-logins = ["Fabien-Chouteau"]
website = "https://github.com/Fabien-Chouteau/usb_embedded"
licenses = "BSD-3-Clause"
tags = ["embedded", "usb", "hid", "midi", "nostd"]

[[depends-on]]
hal = "~0.1.0"
bbqueue = "~0.1.0"

[origin]
commit = "8597a505dd1fd8b28a2e87f069034213ca8a2607"
url = "git+https://github.com/Fabien-Chouteau/usb_embedded.git"

