description = "GObject-based multi-platform GUI toolkit (v3)"
name = "libgtk3"
licenses = "LGPL-3.0-only"
maintainers = ["chouteau@adacore.com"]
maintainers-logins = ["Fabien-Chouteau"]

[[external]]
kind = "system"
[external.origin."case(distribution)"]
"debian|ubuntu" = ["libgtk-3-dev"]
"fedora" = ["gtk3-devel"]
arch = ["gtk3"]
msys2 = ["mingw-w64-x86_64-gtk3"]
homebrew = ["gtk+3"]
macports = ["gtk3"]

[[external]]
kind = "version-output"
version-command = [ "pkg-config", "--modversion", "gtk+-3.0" ]
version-regexp = "([\\d\\.]+)"
# pkg-config requires further steps to make packages findable by
# dependencies that Alire does not yet support
available = false
