description = "Simple logging to console"
name = "simple_logging"
version = "1.1.0"
origin = "https://github.com/alire-project/simple_logging/archive/v1.1.0.tar.gz"
licenses = []
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]
origin-hashes = ["sha512:4cc7cc190a2c5fe493bd73bcc7e6be8dd43455819ce35eb5c3fc32773c5b8ea8cdaccf1ac16e777e8b35f11b2c58b5773b82942033ba920a5b5680bf37a81cd9"]
