description = "Oracle DB binding for Ada"
name = "matreshka_sql_oracle"
version = "21.0.0"
website = "https://github.com/godunko/matreshka"
authors = ["Vadim Godunko"]
licenses = "BSD-3-Clause"
maintainers = ["Vadim Godunko <vgodunko@gmail.com>", "Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko", "reznikmm"]
project-files = ["build_matreshka_sql_oracle.gpr"]
tags = ["sql", "database", "db", "oracle"]

[[depends-on]]
libclntsh = "any"
matreshka_league = "21.0.0"
matreshka_sql = "21.0.0"

[origin]
url = "git+https://github.com/reznikmm/matreshka-alire"
commit = "642d7f2873eb626a335fe5a5e424f604ccb66726"
