description = "Apollo 11 lunar lander simulator"
name = "eagle_lander"
version = "1.2.0"
licenses = ["GPL 3.0"]
maintainers = ["fabien.choutea@gmail.com"]
maintainers-logins = ["Fabien-Chouteau"]
project-files = ["eagle_lander.gpr"]
tags = ["simulator", "game", "gtk"]

[[depends-on]]
gtkada = "^17"

[origin]
url = "https://github.com/Fabien-Chouteau/eagle-lander/releases/download/v1.2/eagle_lander-1.2.zip"
hashes = ["sha512:578532c24f4945d9ca2372e769c534a6f6fd92293090cecc7ad798b8247a8f52ecd6ffdbf3dd2a12b4210f1401677c480f3e9d603b96418eece6ce461d1f0479"]
