description = "Header files and a static library for Python3"
name = "libpython3dev"
licenses = "PSF-2.0"
maintainers = ["chouteau@adacore.com"]
maintainers-logins = ["Fabien-Chouteau"]

[[external]]
kind = "system"
[external.origin."case(distribution)"]
"debian|ubuntu" = ["libpython3-dev"]
msys2 = ["mingw-w64-x86_64-python"]
