name = "pico_examples"
description = "Examples for Ada on the Raspberry Pi Pico"
version = "0.4.0"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
licenses = "BSD-3-Clause"
tags = ["embedded", "nostd", "pico", "rp2040"]
website = "https://github.com/JeremyGrosser/pico_examples"
auto-gpr-with=false
project-files = [
    "adafruit_feather_rp2040/blink_feather.gpr",
    "adc_hello/adc_hello.gpr",
    "blink/blink.gpr",
    "pimoroni_audio_pack/pimoroni_audio_pack.gpr",
    "pimoroni_rgb_keypad/pimoroni_rgb_keypad.gpr",
    "pimoroni_rgb_keypad_interrupt/pimoroni_rgb_keypad_interrupt.gpr",
    "pio_blink/pio_blink.gpr",
    "pwm/pwm.gpr",
    "spi_loopback/spi_loopback.gpr",
    "timer/timer.gpr",
    "uart_echo/uart_echo.gpr"]

[[depends-on]]
pico_bsp = "~0.4"

[origin]
commit = "49f04edf1ddd163718adaa5cd80611f769249f36"
url = "git+https://github.com/JeremyGrosser/pico_examples.git"

