description = "Portable library for OpenGL, window and input"
name = "libglfw3"

maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

[[external]]
kind = "system"
[external.origin."case(distribution)"]
"debian|ubuntu" = ["libglfw3-dev"]
arch = ["glfw"]
msys2 = ["mingw-w64-x86_64-glfw"]
homebrew = ["glfw"]
macports = ["glfw"]

