description = "Library implementing the deflate method from gzip/PKZIP"
name = "zlib"
authors = ["Jean-loup Gailly", "Mark Adler"]

maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

[[external]]
kind = "system"
[external.origin."case(distribution)"]
"debian|ubuntu" = ["zlib1g-dev"]
msys2 = ["mingw-w64-x86_64-zlib"]
