description = "Library implementing the deflate method from gzip/PKZIP"
name = "zlib"
authors = ["Jean-loup Gailly", "Mark Adler"]
licenses = []
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

[[external]]
kind = "system"
[external.origin."case(distribution)"]
"debian|ubuntu" = ["zlib1g-dev"]
