description = "Tk (Tool Control Language Toolkit)"
name = "libtk"
licenses = "TCL"

authors = ["Simon Wright"]
maintainers = ["Simon Wright <simon@pushface.org>"]
maintainers-logins = ["simonjwright"]

[[external]]
hint = "Please install Tk from source or system packages"
kind="system"
[external.origin."case(distribution)"]
"debian|ubuntu" = ["tk8.6-dev"]
"msys2" = ["mingw-w64-x86_64-tk"]
"homebrew" = ["tcl-tk"]
"macports" = ["tk"]
