description = "Pretty print physical values in properly scaled metric (SI) units."
name = "si_units"
version = "0.1.0"
website = "https://github.heisenbug.eu/si_units"
licenses = ["WTFPL"]
maintainers = ["vinzent@heisenbug.eu"]
maintainers-logins = ["Jellix"]
project-files = ["si_units_lib.gpr"]
tags = ["utilities", "formatting"]
[available."case(distribution)"]
"..." = true
debian = false # Compilation hangs on this system (debian-stable)

[gpr-externals]
BUILD = ["debug", "release"]

[gpr-set-externals]
BUILD = "release"

[origin]
url = "https://github.com/HeisenbugLtd/si_units/archive/v0.1.0.tar.gz"
hashes = ["sha512:f41afc8d41c391a51e6dcff9d075b474aaf871d3555347921d7173fb5efdad26d4447c686c672b65ab156286755e693e1e56ead89bda1aea09c5428135c0efa3"]
