name = "ajunitgen"
version = "1.0.1"
description = "Generator of JUnit-compatible XML reports"

authors = [ "Alejandro R. Mosteo", ]
licenses = "LGPL-3.0-only"
maintainers = [ "alejandro@mosteo.com", ]
maintainers-logins = [ "mosteo", ]

tags = ["junit", "xml"]

[[depends-on]]
xml_ez_out = "^1.6"

[origin]
commit = "080ca96388e12dd7b5863463acbad3dc862e06ee"
url = "git+https://github.com/mosteo/ajunitgen.git"

