description = "X11 client-side library"
name = "libx11"
licenses = []
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

[[external]]
kind = "system"
[external.origin."case(distribution)"]
"debian|ubuntu" = ["libx11-dev"]
