description = "Convenience subprograms to interact with C strings"
name = "c_strings"
version = "1.0.0"
authors = ["Alejandro R. Mosteo"]
licenses = ["LGPL 3.0"]
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

[origin]
url = "https://github.com/mosteo/cstrings/archive/v1.0.tar.gz"
hashes = ["sha512:cf45f76d1f86b2389885f9235af9319130a9a5a1717000db84194fbaaa04e8b033e2cd4c173db8b922af3ee5150a1d7334f531074e215d1a911d3ffc38b85e96"]
