name = "gprbuild"
version = "22.0.1"
description = "The GPRBuild Ada/multilanguage build tool"
maintainers = ["chouteau@adacore.com"]
maintainers-logins = ["Fabien-Chouteau"]

auto-gpr-with = false

[environment]
PATH.prepend = "${CRATE_ROOT}/bin"

[configuration]
disabled = true

[origin."case(os)".linux."case(host-arch)".x86-64]
url = "https://github.com/alire-project/GNAT-FSF-builds/releases/download/gprbuild-22.0.0-1/gprbuild-x86_64-linux-22.0.0-1.tar.gz"
hashes = ["sha256:24dfc1b54655edd4f85589e7e7dbd0bee24d087f25d5b0f13d3224fe7acf85b8"]
binary = true

[origin."case(os)".macos."case(host-arch)".x86-64]
url = "https://github.com/alire-project/GNAT-FSF-builds/releases/download/gprbuild-22.0.0-1/gprbuild-x86_64-darwin-22.0.0-1.tar.gz"
hashes = ["sha256:b1220e2b24ce8fdb28344ed9c79c81c1fd2e7e3b05839d35167ceda54050def3"]
binary = true

[origin."case(os)".windows."case(host-arch)".x86-64]
url = "https://github.com/alire-project/GNAT-FSF-builds/releases/download/gprbuild-22.0.0-1/gprbuild-x86_64-windows64-22.0.0-1.tar.gz"
hashes = ["sha256:c842bbc58b28ad0f1c1f7ba147d59e2c9fc4b8f74355ac734831bc779159b47e"]
binary = true
