[general]
description = "Portable library for OpenGL, window and input"
licenses = []
maintainers = ["alejandro@mosteo.com"]

[3]
    [3.origin.'case(distribution)']
    'debian|ubuntu' = "native:libglfw3-dev"
    '...' = ""
