[general]
description = "GNU TLS library"
licenses = []
maintainers = ["alejandro@mosteo.com"]

['3.5.8']
    ['3.5.8'.origin.'case(distribution)']
    'debian|ubuntu' = "native:libgnutls28-dev"
    '...' = ""
