description = "Drivers for Cortex-M micro-controllers (NVIC, SysTick, etc.)"
long-description = '''# cortex-m

Ada drivers for the peripherals of ARM Cortex-M micro-controllers
(NVIC,\nSysTick, etc.)

This crate is a snapshot of the `Cortex-M` support in [Ada Drivers
Library](https://github.com/AdaCore/Ada_Drivers_Library/tree/master/arch/ARM/cortex_m).

Any bug report, issue, contribution must be adressed to the [Ada Drivers
Library](https://github.com/AdaCore/Ada_Drivers_Library/) repo.

'''

name = "cortex_m"
version = "0.2.0"
licenses = "BSD-3-Clause"
authors=["AdaCore"]
website="https://github.com/AdaCore/Ada_Drivers_Library/"
maintainers = ["chouteau@adacore.com"]
maintainers-logins = ["Fabien-Chouteau"]
project-files = ["cortex_m0.gpr", "cortex_m4.gpr", "cortex_m4f.gpr", "cortex_m7.gpr"]
tags = ["embedded", "arm", "nostd"]

auto-gpr-with=false # User has to select only one project file

[[depends-on]]
hal = "^0.1.0"

[origin]
commit = "2b6398536e8c606cb5a56259affbcb4a273c59ca"
url = "git+https://github.com/Fabien-Chouteau/cortex-m.git"

