description = "Library to manipulate with XML streams and documents"
name = "matreshka_xml"
version = "21.0.0"
website = "https://github.com/godunko/matreshka"
authors = ["Vadim Godunko"]
licenses = "BSD-3-Clause"
maintainers = ["Vadim Godunko <vgodunko@gmail.com>", "Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko", "reznikmm"]
project-files = ["build_matreshka_xml.gpr"]
tags = ["xml", "dom", "catalog", "templates", "html5"]

[[depends-on]]
matreshka_league = "21.0.0"

[origin]
url = "git+https://github.com/reznikmm/matreshka-alire"
commit = "fbca8dc8c20531b101403df03352f1dfb70791c6"
