name = "libhello"
description = "Basic library demonstration project"
version = "1.0.1"
tags = ["hello", "demo", "library"]
licenses = "MIT"
website = "https://github.com/alire-project/libhello"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]

[origin]
commit = "3c15bc7f3df22298077c9e96f178adc2829feb42"
url = "git+https://github.com/alire-project/libhello.git"

# We use this crate as a trigger to conveniently test minor changes to
# metaprocesses of the CI of the repository itself.
# Last touch: 2024-10-13 13:53 CET
