description = "Example for the GESTE game engine"
name = "geste_examples"
version = "1.0.0"
website = "https://github.com/Fabien-Chouteau/GESTE-examples"
authors = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
licenses = ["BSD 3-Clauses"]
maintainers = ["fabien.chouteau@gmail.com"]
maintainers-logins = ["Fabien-Chouteau"]
project-files = ["platformer/platformer.gpr", "RPG/RPG.gpr", "racing/racing.gpr"]

[[depends-on]]
geste = "^1.0.0"
sdlada = "^2.3.1"

[origin]
url = "https://github.com/Fabien-Chouteau/GESTE-examples/releases/download/v1.0.0/GESTE_Examples-1.0.0.zip"
hashes = ["sha512:2d94ac6de0a7d5c7087d46d3f276ed69e35b3b22b9322a7e53031ec77a18e46b90162372182401ee4078923ffefb884eb2f1c11a6c00c7727a65e7ee4fe6fe83"]
