description = "Pick a file with probability proportional to its size"
name = "rsfile"
version = "1.0.0"
authors = ["alejandro@mosteo.com"]
executables = ["rsfile"]
licenses = ["GPL 3.0"]
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

[origin]
url = "https://github.com/mosteo/rsfile/archive/v1.0.0.tar.gz"
hashes = ["sha512:41a4d1bf04d1b06634d4c8b33a1b5ee2c9b9e3c6fd3570d306df16a5f960748efd819c72f7295f65c1ebe8e5b30df0366c5f292abffdee96835b95d311b68e2c"]
