description = "Simple DirectMedia Layer development files"
name = "libsdl2"

maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

[[external]]
kind = "system"
    [external.origin.'case(distribution)']
    'debian|ubuntu' = ["libsdl2-dev"]
    'arch' = ["sdl2"]
    'homebrew' = ["sdl2"]
    'macports' = ["libsdl2"]
    'msys2' = ["mingw-w64-x86_64-SDL2"]
