name = "asfml"
description = "An Ada binding to SFML, the Simple and Fast Multimedia Library"
version = "2.5.5"
long-description = """
[![ASFML logo](https://raw.githubusercontent.com/mgrojo/ASFML/master/images/ASFML_Logo.svg)](https://www.sfml-dev.org)
![Ada (GNAT)](https://github.com/mgrojo/ASFML/workflows/Ada%20(GNAT)/badge.svg)
[![Gitter chat](https://badges.gitter.im/gitterHQ/gitter.png)](https://gitter.im/ada-lang/Lobby)
[![Mentioned in Awesome Ada](https://awesome.re/mentioned-badge.svg)](https://github.com/ohenley/awesome-ada)

ASFML is an Ada semi-thick binding to the
[SFML](https://www.sfml-dev.org/) library. It uses Ada types and
portable defined types which eliminates the inclusion of Ada interface
libraries, but most of the functions are directly imported.

# Documentation
Generated API documentation can be consulted [online](https://mgrojo.github.io/ASFML/doc/).

The Ada API follows the [CSFML](https://26.customprotocol.com/csfml/index.htm) interface, but
with some changes and additions for ease of use.

Applicability of the [SFML documentation](https://www.sfml-dev.org/learn.php) is usually straightforward.

"""

authors = ["Manuel Gomez", "Dan Lee Vazquez Garcia"]
maintainers = ["Manuel Gomez <mgrojo@gmail.com>"]
maintainers-logins = ["mgrojo"]

licenses = "custom-zlib-acknowledgement"
website = "https://mgrojo.github.io/ASFML/"
tags = ["audio", "games", "opengl", "cross-platform", "multimedia", "binding", "graphics", "sfml"]

[[depends-on]]
libcsfml = "^2.5.2"

[origin]
commit = "a751457f9eb11b32a4024d48d24d99dc25089c05"
url = "git+https://github.com/mgrojo/ASFML.git"

