name = "rp2040_hal"
description = "Drivers and HAL for the RP2040 micro-controller family"
version = "0.5.0"
licenses = "BSD-3-Clause"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
tags = ["embedded", "nostd", "rp2040", "raspberrypi", "drivers"]
website = "https://github.com/JeremyGrosser/rp2040_hal"

[[depends-on]]
cortex_m = "~0.3"
hal = "~0.1"

[origin]
commit = "a3d897b1910a38f41046e47ea98f21c9e3a00912"
url = "git+https://github.com/JeremyGrosser/rp2040_hal.git"

