name = "gnatcoll_syslog"
version = "21.0.0"
description = "GNAT Components Collection - syslog binding"
website = "https://github.com/adacore/gnatcoll-bindings"
authors = ["AdaCore"]
licenses = "GPL-3.0-only WITH GCC-exception-3.1"
maintainers = ["chouteau@adacore.com"]
maintainers-logins = ["Fabien-Chouteau"]
project-files = ["syslog/gnatcoll_syslog.gpr"]
tags = ["gnatcoll", "bindings", "syslog", "logging"]

[gpr-externals]
GNATCOLL_BUILD_MODE = ["DEBUG", "PROD"]
LIBRARY_TYPE = ["static", "relocatable", "static-pic"]

[available.'case(os)']
'windows' = false
'...' = true

[[depends-on]]
gnatcoll = "~21.0.0"

[origin]
url= "https://github.com/AdaCore/gnatcoll-bindings/archive/v21.0.0/gnatcoll-bindings-21.0.0.zip"
hashes=['sha512:0278508bd697f1334d2b3efb62ae731fda105d07eae02c5e260f7183c561a38d69bf087f9562fd2df3269d87b8732625d7a9a00c130259edc1a6614bf115910d']
