description = "\"Hello, world!\" demonstration project"
name = "hello"
version = "1.0.1"
origin = "https://github.com/alire-project/hello/archive/v1.0.1.tar.gz"
licenses = []
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]
origin-hashes = ["sha512:dcc36a2f6f483fab49a73db30247cfd6b53338adb45d728827573a84894456cb65ac29e64d276f38c8c73a7574f871d1d384ef4b9a2c65d3f433501068b95ad9"]

[[depends-on]]
libhello = "^1.0"
