description = "Ada binding for the GTK+ GUI"
name = "gtkada"
licenses = []
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

[[external]]
kind = "system"
[external.available."case(toolchain)"]
user = false
[external.origin."case(distribution)"]
debian = ["libgtkada18-dev"]
ubuntu = ["libgtkada16.1.0-dev"]
