description = "Ada General Purpose Library with a robotics flavor"
name = "agpl"
version = "1.0.0"
authors = ["alejandro@mosteo.com"]
licenses = ["LGPL 3.0"]
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

[[depends-on]]
libgsl = "any"

[gpr-externals]
Agpl_Include_Boost = ["True", "False"]
Agpl_Include_Concorde = ["True", "False"]
Agpl_Include_Db = ["True", "False"]
Agpl_Include_PngIO = ["True", "False"]

[origin]
url = "https://github.com/mosteo/agpl/archive/v1.0.0.tar.gz"
hashes = ["sha512:b5da332019cb2a2f91540bfe570f8820ce9d56e93449d1839e0f2e1c4d52d9bc759ac78826887c6da038dc23bd1f7444ac04c0518d6280ae718e6ce4f9222881"]
