[general]
description = "GL Object Based Engine for 3D in Ada"
licenses = []
authors = ["Gautier de Montmollin"]
website = "https://globe3d.sourceforge.io/"
maintainers = ["alejandro@mosteo.com"]

    [general.available.'case(os)']
    linux = true

[20180111]
origin = "git+https://github.com/svn2github/GLOBE_3D.git@93f7185130e2fb0db7f1f7e67eaf1b6ca561d651"
project-files = ["globe_3d.gpr"]

    [20180111.depends-on]
    glut = "^2.8.1"

    [20180111.gpr-externals]
    OS_Kind = ["linux", "macosx", "win32"]

    [20180111.gpr-set-externals.'case(os)']
    linux = { OS_Kind = "linux" }
