name = "raylib"
description = "Ada bindings for Raylib"
version = "0.1.0"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = ["raylib", "gamedev", "binding"]

# This release is broken and should not be used anymore
available = false

[[depends-on]]
gnat = ">=12 & <2000"

[origin]
commit = "d5a6702eec1774ee3753672e62fbb99d88ef893a"
url = "git+https://github.com/Fabien-Chouteau/raylib-ada.git"

