description = "Ada Semantic Interface Specification or ASIS (library part)"
name = "asis"
version = "2018.0.0"
website = "https://www.adacore.com/download/more"
authors = ["AdaCore"]
licenses = ["GPL 3.0"]
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]
project-files = ["asis.gpr"]

[[actions]]
type = "post-fetch"
command = ["make", "setup-snames"]

[[depends-on]]
gnat = "=2018"
make = "any"

[origin]
url = "https://community.download.adacore.com/v1/c338044768412af787c8cff13c0d952ed688df11?filename="
archive-name = "asis-gpl-2018-20180524-src.tar.gz"
hashes = ["sha512:e00750adf17df8d534f0e561d129002d8b3c9efd6ba9c8d6768840d1399933271d748bafb7358a45d0a520620a335e669a6c2770ed89660bb319b609961a433a"]
