name = "gnat_native"
version = "12.1.1"
provides = ["gnat=12.1.1"]
description = "The GNAT Ada compiler - Native"
maintainers = ["chouteau@adacore.com"]
maintainers-logins = ["Fabien-Chouteau"]
licenses = "GPL-3.0-or-later AND GPL-3.0-or-later WITH GCC-exception-3.1"

auto-gpr-with = false

[configuration]
disabled = true

[environment]
PATH.prepend = "${CRATE_ROOT}/bin"

[origin."case(os)".windows."case(host-arch)".x86-64]
url = "https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnat-12.1.0-1/gnat-x86_64-windows64-12.1.0-1.tar.gz"
hashes = ["sha256:a0529ef7c4196f5469daa855719c64f2e4d44aa31086c4f0101c3724e9b93fa7"]
binary = true

[origin."case(os)".macos."case(host-arch)".x86-64]
url = "https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnat-12.1.0-1/gnat-x86_64-darwin-12.1.0-1.tar.gz"
hashes = ["sha256:da46195d3a6b0d8d9c2c5380a8aa82912a6910663377a028be386243c129782a"]
binary = true

[origin."case(os)".linux."case(host-arch)".x86-64]
url = "https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnat-12.1.0-1/gnat-x86_64-linux-12.1.0-1.tar.gz"
hashes = ["sha256:df1f36b306359d528799b1de8629a793523347a90c9d4b72efd23c62a7279555"]
binary = true
