description = "Ada LZMA Library Binding"
name = "lzmada"
version = "1.1.0"
origin = "https://github.com/stcarrez/ada-lzma/archive/1.1.0.tar.gz"
licenses = ["MIT"]
maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]
project-files = [".alire/lzmada.gpr"]
origin-hashes = ["sha512:1344289480d43e12622c3ae822d9b4a34d927219341eafff2f80151f2ee6613aac6599d3ee46f602869d1f498129fd0607b688951d6cbf97b24b48af2cb44047"]

[gpr-externals]
BUILD = ["distrib", "debug", "optimize", "profile", "coverage"]
LZMA_LIBRARY_TYPE = ["relocatable", "static", "static-pic"]
