# Please read the TESTING file before modifying this file

# Show differences between the submitted manifest and the previous
# release of the same crate, to enable easier catching of problems

name: Diff release

env:
  CHECKS_ORG: alire-project
  CHECKS_REPO: alire-index-checks
  ALR_VERSION: 1.2.2

on:
  pull_request:
    paths:
      - 'index/**.toml'

jobs:

  DIFF:

    runs-on: ubuntu-latest

    steps:
    - name: Check out alire-index
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        # Needed to be able to diff and obtain changed files. Furthermore, we
        # need the full history or else grafted partial branches confuse the
        # changed files detector

    - name: Check out alire-index-checks
      uses: actions/checkout@v3
      with:
        repository: ${{env.CHECKS_ORG}}/${{env.CHECKS_REPO}}
        ref: ${{github.base_ref}}
        path: ${{env.CHECKS_REPO}}

    - name: Set up stable `alr`
      if: contains(github.base_ref, 'stable-')
      uses: alire-project/setup-alire@v2
      with:
        toolchain: --disable-assistant # We don't need the compiler
        version: ${{env.ALR_VERSION}}

    - name: Set up devel `alr`
      if: contains(github.base_ref, 'devel-')
      uses: alire-project/setup-alire@v2
      with:
        toolchain: --disable-assistant # We don't need the compiler
        branch: master

    - name: <<DIFF RELEASES>>
      run: ${{env.CHECKS_REPO}}/scripts/diff-release.sh || true # No deal breaker if failed
      shell: bash
