name: Check PR
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master

    - uses: alire-project/check-author@master
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

    - name: Set up stable `alr`
      if: contains(github.base_ref, 'stable-')
      uses: alire-project/setup-alire@latest-stable

    - name: Set up GNAT for devel `alr`
      if: contains(github.base_ref, 'devel-')
      uses: ada-actions/toolchain@ce2020
      with:
        distrib: fsf

    - name: Set up devel `alr`
      if: contains(github.base_ref, 'devel-')
      uses: alire-project/setup-alire@latest-devel

    - run: alr index --list

    - run: alr index --add=. --name=local_index

    # Check index contents for unknown config variables
    - run: alr index --check

    - run: alr index --update-all 

    - run: alr search --crates
